### ISSUE TITLE
A wishlist

### ISSUE THREAD

**Issue by putianyi889** [scheinerman/LinearFractionalTransformations.jl#1]
- Use [parametric types](https://docs.julialang.org/en/v1/manual/types/#Parametric-Types) for better type flexibility.
- Use 4 properties, a tuple or a [static array](https://github.com/JuliaArrays/StaticArrays.jl) for better performance.
- Move from `LFT(a,aa,b,bb,c,cc)` to `LFT(a=>aa, b=>bb, c=>cc)` which is more intuitive.
- Add a subtype `AffineTransform`.

I could help if you are busy.

**Comment by scheinerman** [comment]
Thanks for your interest. Some replies ... 


> * Use [parametric types](https://docs.julialang.org/en/v1/manual/types/#Parametric-Types) for better type flexibility.

I don't understand what you're suggesting.

> * Use 4 properties, a tuple or a [static array](https://github.com/JuliaArrays/StaticArrays.jl) for better performance.

Are you suggesting that I replace `M::Array{Complex{Float64},2}` with something like this: `SMatrix{2,2,Complex{Float64},4}`? How would that help?

> * Move from `LFT(a,aa,b,bb,c,cc)` to `LFT(a=>aa, b=>bb, c=>cc)` which is more intuitive.

Can we add that as a constructor without breaking anything else? If so, I think that would be nice.


> * Add a subtype `AffineTransform`.

Rather not add to the package and there already is a Julia [AffineTransforms](https://github.com/timholy/AffineTransforms.jl) package. 


> 
> I could help if you are busy.

**Comment by putianyi889** [comment]
> I don't understand what you're suggesting.

This package currently only supports `Float64`. Parametric types allows supporting more data types.

> How would that help?

`getproperty` or `getindex` of static objects are much faster than dynamic objects like `Array`.

**Comment by scheinerman** [comment]
OK. Let me think about these. I'm wary of changes that might break code already depending on these.

**Comment by scheinerman** [comment]
Adding the constructor `LFT(a=>aa, b=>bb, c=> cc)` was easy. I've done that. I'm open to the idea of parametric types. I can see how that might be helpful for exact arithmetic. Can you suggest how to change this part of the code:
```
struct LFT
    M::Array{Complex{Float64},2}
    function LFT(a, b, c, d)
        if isinf(a) || isinf(b) || isinf(c) || isinf(d)
            error("Arguments must be finite: " * string((a, b, c, d)))
        end

        if a * d - b * c == 0
            error("Singularity detected: " * string((a, b, c, d)))
        end

        new([a b; c d])
    end
end
```
I have four other packages that depend on this one, and I'm concerned that nothing breaks as a result.

**Comment by putianyi889** [comment]
What causes minimal changes would be
```julia
struct LFT{T} where T<:Real
    M::Array{Complex{T},2}
    ...
end
```

**Comment by scheinerman** [comment]
Didn't work. I tried changing lines 13-26 to this:
```
struct LFT{T} where {T<:Real}
    M::Array{Complex{T},2}
    function LFT(a, b, c, d)
        if isinf(a) || isinf(b) || isinf(c) || isinf(d)
            error("Arguments must be finite: " * string((a, b, c, d)))
        end

        if a * d - b * c == 0
            error("Singularity detected: " * string((a, b, c, d)))
        end

        new([a b; c d])
    end
end
```
and then got this error message:
```
julia> using LinearFractionalTransformations
Precompiling LinearFractionalTransformations
        Info Given LinearFractionalTransformations was explicitly requested, output will be shown live 
ERROR: LoadError: syntax: invalid type signature around /Users/ers/.julia/dev/LinearFractionalTransformations/src/LinearFractionalTransformations.jl:13
Stacktrace:
 [1] top-level scope
   @ ~/.julia/dev/LinearFractionalTransformations/src/LinearFractionalTransformations.jl:13
 [2] include
   @ ./Base.jl:495 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2222
 [4] top-level scope
   @ stdin:3
in expression starting at /Users/ers/.julia/dev/LinearFractionalTransformations/src/LinearFractionalTransformations.jl:3
in expression starting at stdin:3
  ✗ LinearFractionalTransformations
  0 dependencies successfully precompiled in 4 seconds
```

**Comment by putianyi889** [comment]
Let me create a pull request.

**Comment by scheinerman** [comment]
Please don't. I'd rather you sent me code. I have another idea that seems to be working:
```
struct LFT{T} 
    M::Array{T,2}
    function LFT(a, b, c, d)
        if isinf(a) || isinf(b) || isinf(c) || isinf(d)
            error("Arguments must be finite: " * string((a, b, c, d)))
        end

        if a * d - b * c == 0
            error("Singularity detected: " * string((a, b, c, d)))
        end
        a,b,c,d = promote(a,b,c,d)
        T = typeof(a)
        new{T}([a b; c d])
    end
end
```

**Comment by scheinerman** [comment]
The trouble with this new code is that exact `LFT` applied to an exact argument, gives a floating point answer:
```
julia> f = LFT(2//3, 0im , 5+im, 4)
LFT( 2//3 + 0//1*im , 0//1 + 0//1*im , 5//1 + 1//1*im , 4//1 + 0//1*im )

julia> f(1)
0.07317073170731707 - 0.008130081300813007im
```

**Comment by scheinerman** [comment]
And I think I know how to fix it.
```
julia> f = LFT(2//3, 0im , 5+im, 4)
LFT( 2//3 + 0//1*im , 0//1 + 0//1*im , 5//1 + 1//1*im , 4//1 + 0//1*im )

julia> f(1)
3//41 - 1//123*im
```

**Comment by putianyi889** [comment]
This passes the tests
```julia
struct LFT{T<:Real}
    M::Array{Complex{T},2}
    function LFT{T}(a::Complex{T}, b::Complex{T}, c::Complex{T}, d::Complex{T}) where T
        if isinf(a) || isinf(b) || isinf(c) || isinf(d)
            error("Arguments must be finite: " * string((a, b, c, d)))
        end

        if a * d - b * c == 0
            error("Singularity detected: " * string((a, b, c, d)))
        end

        new{T}([a b; c d])
    end
end
LFT(a::Number, b::Number, c::Number, d::Number) = LFT(promote(a, b, c, d)...)
LFT(a::T, b::T, c::T, d::T) where T<:Real = LFT(complex(a), complex(b), complex(c), complex(d))
LFT(a::Complex{T}, b::Complex{T}, c::Complex{T}, d::Complex{T}) where T<:Real = LFT{T}(a, b, c, d)
```

**Comment by scheinerman** [comment]
I'm wondering if there's any need to force the entries in the matrix to be Complex. Seems to work fine if, for example, the entries are real.

**Comment by putianyi889** [comment]
I'm not sure how Julia deals with it. It's great if it's smart.
Julia seems to have specific routine for real-complex multiplication so it'll be fine.

**Comment by scheinerman** [comment]
I'm going to push out this update. I don't know if it's worth the effort to convert to static arrays.

**Comment by scheinerman** [comment]
Maybe not quite. I need to look at implications. For example, I get this now:
```
julia> f = LFT(1,2,3,5)
LFT( 1 , 2 , 3 , 5 )

julia> g = LFT(1//1,2,3,5)
LFT( 1//1 , 2//1 , 3//1 , 5//1 )

julia> f==g
false
```
Ugh.


**UPDATE!!! I fixed that. I'll hunt for more bugs before releasing.**

**Comment by putianyi889** [comment]
It is indeed an annoying feature of Julia.
```julia
julia> 1/3 == 1//3
false
```

**Comment by scheinerman** [comment]
OK. I just submitted 0.1.4 to be registered. I'm wondering if it should be 0.2.0? Not exactly a breaking change though.

**Comment by putianyi889** [comment]
It's a change of struct definition so it's breaking.

**Comment by scheinerman** [comment]
I've already sent it in. Since the interface hasn't changed, it shouldn't cause problems. Next issue is to think about the switch to a static array. I'm wondering if that's really going to make things better.

**Comment by scheinerman** [comment]
I think it's working and will now release as version 0.2.0

**Comment by scheinerman** [comment]
Had a bit of a problem registering, but 0.2.0 is now available.
